packages:
  - apps/*
  - packages/*
allowBuilds:
  '@sentry/cli': true
  esbuild: true
  sharp: true
  '@prisma/engines': true
  prisma: true
ignoredBuiltDependencies:
  - '@prisma/engines'
  - prisma
overrides:
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
